# This is a basic workflow that is manually triggered

name: Build and test application

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build and test application
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Setup dotnet 8.0.0
              uses: actions/setup-dotnet@v4
              with: 
                dotnet-version: 8.0.x
            - name: Install workload
              run: dotnet workload restore
            - name: Restore dependencies
              run: dotnet restore ./Quiz.ForNative/Quiz.ForNative.sln
            - name: Build
              run: dotnet build ./Quiz.ForNative/Quiz.ForNative.sln --no-restore
